version: '3.9'
services:
  webpage:
    container_name: webpage    
    build: .
    image: webpage
    expose:
      - 5000
    volumes:
      - .:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 81:81
    links:
      - webpage
    restart: always